services:
  item_pool_mongodb:
    image: mongo:latest
    container_name: item_pool_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    expose:
      - ${MONGO_PORT}:27017
    volumes:
      - "mongodata:/bitnami/mongodb/:rw"
    restart: unless-stopped
    networks:
      - default

volumes:
  mongodata:
