[project]
name = "itempoolapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pymongo>=4.15.3",
    "sqlglot>=27.29.0",
    "textstat>=0.7.11",
]
